### ISSUE TITLE
 The training results look very poor.

### ISSUE THREAD

**Issue by Yuhuoo** [city-super/GSDF#11]
Thanks for your great work. I tried to reproduce two scenes, "bicycle" and "room", on mipnerf360 using this project, and the results are very poor, which is quite puzzling to me. How were the results in your paper obtained?

![image](https://github.com/user-attachments/assets/84187d95-3f8b-4b06-ab7c-4c9a0dc60c98)
![d1519aa21ea48249e37a54ac7bfac8f](https://github.com/user-attachments/assets/c93f2049-d456-45fd-9a3d-ca53b9eade33)

![image](https://github.com/user-attachments/assets/656b32fc-1c51-4ea7-9bd8-a3266ba4c1c9)
![3b6788bc7959812f1e60009bdfd1ab1](https://github.com/user-attachments/assets/c660ab1b-9693-40a5-929b-289277b246c8)

**Comment by Yuhuoo** [comment]
Hi, I ran tests on the drjohnson scene in the deep blending dataset again. In the obtained mesh file, I noticed that the scene's mesh seems to be embedded within the cube mesh. How do I extract the individual scene mesh from this cube?

![37cc6462e80af084aa144aec119b7f5](https://github.com/user-attachments/assets/f6bad3a2-c891-4acf-8f32-da71e0330f65)

**Comment by MulinYu** [comment]
The psnr is only around 15, which is not normal, please make sure your data and config are right. For visualizing the inside of the room, please zoom in using the mouse wheel.

**Comment by Yuhuoo** [comment]
Thank you for your reply. I have rerun the test for the bicycle scene, and it is working properly.
However, when trying to visualize the inside of the room, I attempted to zoom in using the mouse wheel, but still couldn't see the internal mesh of the room, and because the mesh is very large, it becomes very laggy when zooming in. Could you please help to solve this visualization issue? For example, by extracting only the mesh of the room instead of exporting a cube?

**Comment by MulinYu** [comment]
Maybe use Meshlab to visualize them. BTW, the visualization of indoor scenes is not an issue of the project.
