### ISSUE TITLE
How to reduce GPU memory usage

### ISSUE THREAD

**Issue by CanCanZeng** [city-super/GSDF#13]
Hello, I am trying to rebuild the Barn scene using the `train.sh` script, but an OOM error occurs every time it runs to around 20K. I am using a NVIDIA 4080 graphics card with 16GB of video memory. How can I reduce the usage of video memory so that my machine can also run GSDF?

**Comment by MulinYu** [comment]
Maybe reduce the resolution of hash grid in 'xyz_encoding_config' but it will lead to degraded quality.

**Comment by CanCanZeng** [comment]
Thank you for your reply!
