### ISSUE TITLE
Could you add config files of TNT dataset?

### ISSUE THREAD

**Issue by ThePassedWind** [city-super/GSDF#14]
I only saw two config files of TNT dataset.

**Comment by ThePassedWind** [comment]
Plus, have you tried your method on Nerf Synthetic dataset?
If so, could you please share the configs of this dataset?

**Comment by MulinYu** [comment]
![tnt](https://github.com/user-attachments/assets/883f758b-15fc-4b46-804c-8f4b10427234)

**Comment by ThePassedWind** [comment]
> ![tnt](https://private-user-images.githubusercontent.com/26922343/383794106-883f758b-15fc-4b46-804c-8f4b10427234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDgyNjcsIm5iZiI6MTczMDk0Nzk2NywicGF0aCI6Ii8yNjkyMjM0My8zODM3OTQxMDYtODgzZjc1OGItMTVmYy00YjQ2LTgwNGMtOGY0YjEwNDI3MjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAyNTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NjFmY2MyYjIyNTliZmMzZmYzMzM1OGQ5ZDk1MjkwYWExOTUyZjlhODFjYWEzMDQwMDY4NjMzNGUzYmZmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bpyWZTNo9v1O0MyM5X0e-3w4T8jmjOCx2ZRH1weKi2E)

I'm sorry for my oversight. I found there are 6 scenes of TNT dataset in your baselines(eg: 2DGS), so I thought GSDF would be as same as them.
Thanks for your reply!
