### ISSUE TITLE
How can i get mesh file

### ISSUE THREAD

**Issue by ddenglina** [city-super/GSDF#15]
Thanks for you greak work! 

I get properly traning results. I want to know where mesh file. Or how can I get mesh file?
![捕获](https://github.com/user-attachments/assets/573493b3-c174-4055-9ee0-f55bb2cd7a39)

**Comment by Zhaoyibinn** [comment]
mesh filed is trained by neus, saved in 'exp' file(deault)

**Comment by ddenglina** [comment]
> mesh filed is trained by neus, saved in 'exp' file(deault)

Thanks, I got it.
