### ISSUE TITLE
有关模型的训练

### ISSUE THREAD

**Issue by trainable** [city-super/GSDF#7]
我尝试训练db_drjohnson并使用您db_drjohnson.yaml中的参数，训练到15000伦直接停止了。
如图所示
![屏幕截图 2024-10-17 182550](https://github.com/user-attachments/assets/cac20b6c-ff88-4dba-8370-5d338b7a5f79)
请问是参数设置还是什么问题？
顺便问一下，您的neus模型保存在哪里

**Comment by trainable** [comment]
这里的loss=nan,是正常的，还是非正常导致训练停止了

**Comment by MulinYu** [comment]
不正常，保存在exp文件夹

**Comment by MulinYu** [comment]
Closing since no response.
